# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.txt'
      - '*.vsix'
      - '*.doc'
      - '*.yml'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.txt'
      - '*.vsix'
      - '*.doc'
      - '*.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        defines:
          - ""
    env:
      WIX_NAME: "wixtoolset"
      WIX_VER: "3.11.2"
      VC: "call vcvars32.bat && cd Libraries"
      GIT: "https://github.com"
      UPLOAD_ARTIFACT: "true"
      ONLY_CACHE: "false"
      AUTO_CACHING: "1"
      MANUAL_CACHING: "2"
    steps:
    - uses: actions/checkout@v2
    - name: 获取仓库名称
      shell: bash
      run: echo ::set-env name=REPO_NAME::${GITHUB_REPOSITORY##*/} 
        
    - name: 初始化Java1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven进行打包
      run: mvn -B package -DskipTests --file pom.xml
 
    - name: 移动打包制品.
      if: env.UPLOAD_ARTIFACT == 'true'
      run: |
        cd target
        mkdir artifact
        move *.jar artifact\result.jar
    - uses: actions/upload-artifact@master
      name: 上传打包制品.
      if: env.UPLOAD_ARTIFACT == 'true'
      with:
        name: result.jar
        path: target\artifact\
